aliyun:
  oss:
    end-point: http://oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAIAbTcMC3WqeU6
    access-secret: RFu6Nqmlwonp7e6Cid1iunOJwDVcaV
    bucket: comico-cloud
    cname: http://img.comicont.com/
    part-size: 102400
  sms:
    access-key-id: LTAIAbTcMC3WqeU6
    access-secret: RFu6Nqmlwonp7e6Cid1iunOJwDVcaV
    sign-name: 高美高
server:
  port: 8787
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/comico-erp?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    username: root
    password: hch123456
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-test-query: select 1
      data-source-properties:
        cache-prep-stmts: true
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  resources:
    static-locations: classpath:/static/
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
feign:
  httpclient:
    enabled: true
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000


